name 'kloxo-mr'
maintainer 'Adam BALAZS'
maintainer_email 'adam@balazsasd.net'
license 'all_rights'
description 'Installs/Configures kloxo-mr'
long_description 'Installs/Configures kloxo-mr'
version '0.1.0'

depends 'yum-centos', '~> 0.4.12'
depends 'selinux'
